#!/usr/bin/php
<?php

// This is CLI PHP, launch it and it will forever ask Pilot.ino for pin 13
// and launch your program when result is 0 (button pressed = 0)
// Stop with CTRL-C

// This example uses the internal Pull Up resistors to limit circuitry
// it means you just have to connect one button wire to pin 13, and the other wire to GND
// it sets pin 13 mode to input, but do a digitalWrite to HIGH (=activate pullup)
// ( $UDOOArduino->dir('in',$BUTTON_PIN); $UDOOArduino->set('d',$BUTTON_PIN,'hi');)
// then it listens to LOW if button pressed and HIGH if button released (reversed)




    // configure here, executed below
    $SCRIPT_TO_LAUNCH='ls -al';
    $BUTTON_PIN=20; // connect button wire to pin 13 as written on the board, other wire to GND
    $LED_PIN=19; // just a feedback led
    $BUTTON_DOWN='0'; //inverted to avoid resistor
    $BUTTON_UP='1';
    
    
    $isPressed=FALSE;
 
    require('pilotino.php');
    $UDOOArduino=new PilotIno('/dev/ttymxc3',115200);
  
    $UDOOArduino->dir('in',$BUTTON_PIN); // pin inward reversed as digital sensor
    $UDOOArduino->set('d',$BUTTON_PIN,'hi'); // activate pin internal pullup resistor
    $UDOOArduino->dir('out',$LED_PIN); // pin outward as led
    $UDOOArduino->set('d',$LED_PIN,'lo');
 	
    $lastButton=$BUTTON_UP;
    while(TRUE) { // CTRL-C to exit
            $button=$UDOOArduino->get('d',$BUTTON_PIN);
            // echo($button);
            // Only at first press, not every cycle!
            if($lastButton!=$button) {
            	if($button==$BUTTON_DOWN) {
          			$UDOOArduino->set('d',$LED_PIN,'hi');
            		$isPressed=TRUE;
               		$res=`$SCRIPT_TO_LAUNCH`; // Executing script
                	// wait .5 sec to avoid button "bouncing" (http://www.elexp.com/t_bounc.htm)
                	echo($res);
                	usleep(0500000);
         			$UDOOArduino->set('d',$LED_PIN,'lo');
                } else if($button==$BUTTON_UP) {
            		$isPressed=FALSE;
            		// wait .5 sec to avoid button "bouncing" (http://www.elexp.com/t_bounc.htm)
                 	usleep(0500000);
               }
            }
            usleep(0010000); // 1/100 of sec
            $lastButton=$button;
    }
    $UDOOArduino=null; // never here
?>