#!/usr/bin/php
<?php
        require('pilotino.php');
        $UDOOArduino=new PilotIno('/dev/ttymxc3',115200); // or 19200 57600 115200 same as SERIAL_SPEED constant in pilot.ino
        
        $UDOOArduino->dir('out',5);
        $UDOOArduino->dir('out',6);
        $UDOOArduino->dir('out',7);
        $UDOOArduino->dir('out',8);
        $UDOOArduino->dir('out',9);
        $UDOOArduino->dir('out',10);
        $UDOOArduino->dir('out',11);
        $UDOOArduino->dir('out',12);
        $UDOOArduino->dir('out',13);
       
        while(TRUE) {
        
                
                $UDOOArduino->set('d',5,'lo');
                $UDOOArduino->set('d',6,'hi');
                $UDOOArduino->set('d',7,'lo');
                $UDOOArduino->set('d',8,'lo');
                $UDOOArduino->set('d',9,'hi');
                $UDOOArduino->set('d',10,'lo');
                $UDOOArduino->set('d',11,'lo');
                $UDOOArduino->set('d',12,'hi');
                $UDOOArduino->set('d',13,'lo');
                usleep(0010000);
                $UDOOArduino->set('d',5,'lo');
                $UDOOArduino->set('d',6,'lo');
                $UDOOArduino->set('d',7,'hi');
                $UDOOArduino->set('d',8,'lo');
                $UDOOArduino->set('d',9,'lo');
                $UDOOArduino->set('d',10,'hi');
                $UDOOArduino->set('d',11,'lo');
                $UDOOArduino->set('d',12,'lo');
                $UDOOArduino->set('d',13,'hi');
                usleep(0010000);
                $UDOOArduino->set('d',5,'hi');
                $UDOOArduino->set('d',6,'lo');
                $UDOOArduino->set('d',7,'lo');
                $UDOOArduino->set('d',8,'hi');
                $UDOOArduino->set('d',9,'lo');
                $UDOOArduino->set('d',10,'lo');
                $UDOOArduino->set('d',11,'hi');
                $UDOOArduino->set('d',12,'lo');
                $UDOOArduino->set('d',13,'lo');
                usleep(0010000);
                
                $sensor=$UDOOArduino->get('a','A0');
                echo($sensor."\n"); // upload to server here
                
        }
        $UDOOArduino=null;
?>
