#!/usr/bin/php
<?php



// What is this?

// Arduino -> serial -> local PHP script (this) -> (proxy) -> public web -> www PHP script


// Example PHP standalone script that reads sensor info from an Arduino over serial
// and sends them to a remote (public) web server, receives commands to execute in return
// and sends them to the Arduino

// The usage scenario is a development board or small PC connected to the internet from
// inside a protected LAN with NAT or firewall. The small PC can only send GET/POST requests out
// it can not be reached from the outside world.

// Developed for UDOO board (linux+Arduino embedded)

// This uploadtest script runs on the small PC and connects to a receiver script on some public web server
// The public web server can receive sensor data from the small PC and return commands to execute
// (turn on/off or dim leds, activate motors, etc..)


// PARAMETERS

$SERVER = 'http://www.pangoo.it/pilotino/receiver.php'; // may not handle well redirects: try www.hostname.com/index.php instead of just hostname.com/
$SENSORS_ANALOG_READ=array('A0'); // send at every call (quicker than waiting for a get command retrieving, and sending results)
$SENSORS_DIGITAL_READ=array(); // send at every call
$SLEEP=1000000; // one sec = 1000000, sleep before reconnect
$LED_CONNECTION=10; // FALSE to disable
$LED_WAIT=9; // FALSE to disable
$LED_SENSOR_FEEDBACK=FALSE; // FALSE to disable
$LINE_SEPARATOR="\n"; // Used by remote script to separate commands


// Init Pilot.ino

require('pilotino.php');
$UDOOArduino=new PilotIno('/dev/ttymxc3',115200); // or 19200 57600 115200 same as SERIAL_SPEED constant in pilot.ino


// Init pin directions: out for connection feedback pins

if($LED_CONNECTION) $UDOOArduino->dir('out',$LED_CONNECTION);
if($LED_WAIT) $UDOOArduino->dir('out',$LED_WAIT);
if($LED_SENSOR_FEEDBACK) $UDOOArduino->dir('out',$LED_SENSOR_FEEDBACK);

// Init pin directions: in for sensors defined in setup params

foreach($SENSORS_ANALOG_READ as $aSensor) {
	// $UDOOArduino->dir('in',$aSensor);
}

foreach($SENSORS_DIGITAL_READ as $aSensor) {
	$UDOOArduino->dir('in',$aSensor);
}
           

// reset things before loop
$results=array(); // no last results to upload at first
$timeStamp=''; // no last timestamp to upload at first

// Go on forever (CTRL-C ends)           

$VARIABLES=array(); // here the server may keep state information between iterations (as an alternative to a database)
           
while(TRUE) {

// Sleep with LED on          

	if($LED_WAIT) $UDOOArduino->set('d',$LED_WAIT,'hi');
	usleep($SLEEP);
	if($LED_WAIT) $UDOOArduino->set('d',$LED_WAIT,'lo');
	
	
// Collect data to send          
           
	$data = array();
	$firstSensor=NULL;
	
	foreach($SENSORS_ANALOG_READ as $aSensor) {
		$sensorVal=$UDOOArduino->get('a',$aSensor);
		$data[$aSensor]=$sensorVal;
		if($firstSensor===NULL) {
			$firstSensor=$sensorVal;
		}
	}
	
	foreach($SENSORS_DIGITAL_READ as $aSensor) {
		$sensorVal=$UDOOArduino->get('d',$aSensor);
		$data[$aSensor]=$sensorVal;
	}
	$data['previous_timestamp']=$timeStamp;
	$timeStamp=str_replace('.','',''.microtime(TRUE)*1000); // str_replace should be useless
	$data['source_time']=$timeStamp;
	$data['previous_results']=implode($LINE_SEPARATOR,$results);
	$data['saved_states']=implode($LINE_SEPARATOR,$VARIABLES);
	
// Package it in a POST wrapper

	// use key 'http' even if you send the request to https://...
	$options = array(
	    'http' => array(
	        'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
	        'method'  => 'POST',
	        'content' => http_build_query($data),
	    ),
	);
	$context  = stream_context_create($options);
	
// And send it
// Led on while waiting for reply

	if($LED_CONNECTION) $UDOOArduino->set('d',$LED_CONNECTION,'hi');
	$connectionResult = file_get_contents($SERVER, false, $context);
	if($LED_CONNECTION) $UDOOArduino->set('d',$LED_CONNECTION,'lo');
	
	// echo($connectionResult);
   // echo("\n");
   $commands=explode($LINE_SEPARATOR,$connectionResult);
   $results=array();
   foreach($commands as $aCommand) {
   	$aCommand=trim($aCommand);
   	if($aCommand=='') continue;
   	if(substr($aCommand,0,3)=='do ') { // to be sure to execute only intended commands, start every line with "do "
   		$results[]=$UDOOArduino->sendCmd(substr($aCommand,3));
   		echo("<do> ".substr($aCommand,3)."\n");
   		$results[]=substr($aCommand,3).' '.$UDOOArduino->sendCmd(substr($aCommand,3));
   		// echo(substr($aCommand,3));
   		// print_r($results);
   	} else if(substr($aCommand,0,5)=='save ') {
   		$aCommand=explode(' ',$aCommand);
   		if(count($aCommand)===3) $VARIABLES[$aCommand[1]]=$aCommand[1].'='.$aCommand[2];
   		else if(count($aCommand)===2) $VARIABLES[$aCommand[1]]=$aCommand[1].'=';
    		echo("<save> ".$aCommand[1].' = '.$aCommand[2]."\n");
  		}
   	
   }
   // $UDOOArduino->dir('out',13);
   if($LED_SENSOR_FEEDBACK && $firstSensor!==NULL) {
		echo($LED_SENSOR_FEEDBACK." -> ".intVal($firstSensor*255/1023));	
   	echo( ': '.trim($UDOOArduino->set('a',12,16)));
  		echo("\n");
	}
   print_r($results);
   echo("\n");

}

// Neverneverland

$UDOOArduino=null; // Uselessuselessline

?>
